#!/bin/bash

DIR=$(basename $(pwd))
DAY=$1

if [ ! $DIR = "advent-of-code-2024" ]; then 
        echo "Wrong directory"
        exit 1
fi

if [ -z $DAY ]; then
        echo "No directory specified"
        exit 1
fi

if [ -d $DAY ]; then
        echo "Directory already exists"
        exit 1
fi

mkdir -pv $1/python
pushd $1
cargo new rust
pushd rust
pushd src
cp -v ../../../templates/main.rs ./main.rs
popd
popd
pushd python
/usr/bin/python3 -m venv venv
cp -v ../../templates/main.py ./
popd
cp -v ../day-03/.gitignore ./
popd
